pipeline {
    environment {
        registry = "gigimahu/p-database"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
        dockerFile = 'dockerfile.database'
    }
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/GigiMahu/wantsome-project.git'
            }
        }
        stage('Building Docker image') {
            steps{
                script {
                    dockerImage = docker.build(registry,"-f ./dockerfiles/${dockerFile} .")
                }
            }
        }
        stage('Push Docker image on DockerHub') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}