FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
ENV PG_SQL_VER="14"
RUN apt update && apt upgrade -y
RUN apt install gnupg wget ca-certificates -y

# Add the PostgreSQL PGP key to verify their Debian packages.
# It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
# RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8..
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Add PostgreSQL's repository. It contains the most recent stable release
#  of PostgreSQL.
# RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list

# Install ``python-software-properties``, ``software-properties-common`` and PostgreSQL 14
#  There are some warnings (in red) that show up during the build. You can hide
#  them by prefixing each apt-get statement with DEBIAN_FRONTEND=noninteractive
# RUN apt install -y python-software-properties -y
RUN apt install -y software-properties-common postgresql postgresql-client postgresql-contrib

# Note: The official Debian and Ubuntu images automatically ``apt-get clean``
# after each ``apt-get``

# Run the rest of the commands as the ``postgres`` user created by the ``postgres`` package when it was ``apt-get installed``
USER postgres

# Create a PostgreSQL role named ``drupal`` with ``drupal`` as the password and
# then create a database `drupal` owned by the ``drupal`` role.
# Note: here we use ``&&\`` to run commands one after the other - the ``\``
#       allows the RUN command to span multiple lines.
RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER drupal WITH SUPERUSER PASSWORD 'drupal';" &&\
    createdb -O drupal drupal

RUN mkdir -p /etc/postgresql/${PG_SQL_VER}/main
# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/${PG_SQL_VER}/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/${PG_SQL_VER}/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/${PG_SQL_VER}/main/postgresql.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/${PG_SQL_VER}/bin/postgres", "-D", "/var/lib/postgresql/${PG_SQL_VER}/main", "-c", "config_file=/etc/postgresql/${PG_SQL_VER}/main/postgresql.conf"]