pipeline {
    environment {
        registry = "gigimahu/p-application"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
        dockerFile = 'dockerfile.app'
        dockerRun1 = "docker run \
                        --detach \
                        --network wantsome \
                        --name app1 \
                        ${registry}"
        dockerRun2 = "docker run \
                        --detach \
                        --network wantsome \
                        --name app2 \
                        ${registry}"
    }
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/GigiMahu/wantsome-project.git'
            }
        }
        stage('Building Docker image') {
            steps{
                script {
                    dockerImage = docker.build(registry,"-f ./dockerfiles/${dockerFile} .")
                }
            }
        }
        stage('Push Docker image on DockerHub') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Run Container on Env Server'){
            steps{
                sshagent(credentials: ['env_server']) {
                    sh "ssh -o StrictHostKeyChecking=no jenkins@192.168.56.20 docker network create wantsome"
                    sh "ssh -o StrictHostKeyChecking=no jenkins@192.168.56.20 ${dockerRun1}"
                    sh "ssh -o StrictHostKeyChecking=no jenkins@192.168.56.20 ${dockerRun2}"
                }
            }
        }
    }
}