pipeline {
    environment {
        registry = "gigimahu/p-application"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
        dockerFile = 'dockerfile.application'
        dockerRun = "docker run -d --name app1 ${registry} && docker run -d --name app2 ${registry}"
    }
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/GigiMahu/wantsome-project.git'
            }
        }
        stage('Building Docker image') {
            steps{
                script {
                    dockerImage = docker.build(registry,"-f ./dockerfiles/${dockerFile} .")
                }
            }
        }
        stage('Push Docker image on DockerHube') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Run Container on Env Server'){
            steps{
                sshagent(credentials: ['env_server']) {
                    sh "ssh -o StrictHostKeyChecking=no jenkins@192.168.56.20 ${dockerRun}"
                }
            }
        }
    }
}